# Generated by Django 6.0.2 on 2026-02-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('anomaly_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('severity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyType',
            fields=[
                ('anomalytype_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('building_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('energyreading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('power_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('homeowner', 'Homeowner'), ('technician', 'Technician')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('sensortype_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.anomaly')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='anomaly_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.anomalytype'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.buildingtype')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='energy_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.energyreading'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('installed_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.building')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.sensortype')),
            ],
        ),
        migrations.AddField(
            model_name='energyreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.sensor'),
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.role')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingUser',
            fields=[
                ('building_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartguard.user')),
            ],
        ),
    ]
